---
- name: Install redis
  yum:
   name: '{{ redis_package_name }}'
   state: installed
  when: manage_packages|default(false)

- name: Ensure redis config file exits
  file:
    path: '{{ redis_config_file }}'
    state: file
    owner: '{{ redis_owner }}'

- name: Set listen port at redis config
  replace:
     dest: '{{ redis_config_file }}'
     regexp: '^port.*\n'
     replace: 'port {{ redis_listen_port }}\n'
  notify: Restart redis
  when: (not redis_listen_port == 6379) or
        (manage_packages|default(false))

- name: Add bind interface at the redis config
  lineinfile:
     dest: '{{ redis_config_file }}'
     create: yes
     state: present
     insertafter: 'bind 127.0.0.1'
     line: 'bind {{ redis_interface }}'
  notify: Restart redis
  when: (not redis_interface == '127.0.0.1') or
        (manage_packages|default(false))

- name: Ensure redis is started and enabled at boot
  service:
   name: '{{ redis_service_name }}'
   state: started
   enabled: yes
  when: manage_services|default(false)

- name: register redis firewall  port
  set_fact:
    firewall_ports: >
      {{ firewall_ports + [redis_listen_port] }}
  when: not redis_interface == '127.0.0.1'
