#Include the rabbitmq plugin to be able to create a vhost
- name: Add plugin to manage rabbitmq
  rabbitmq_plugin:
   names: rabbitmq_management
   state: enabled

#It creates the vhost to be used
- name: Create sensu vhost on rabbitmq
  rabbitmq_vhost:
   name: '{{ sensu_rabbitmq_vhost }}'
   state: present
  notify:
      - restart rabbitmq

# Add user to server and assign full access control on / vhost.
# The user doesn't have permission rules for other vhosts
- name: Configure rabbitmq permissions
  rabbitmq_user:
    user: '{{ sensu_rabbitmq_user }}'
    password: '{{ sensu_rabbitmq_password }}'
    vhost: '{{ sensu_rabbitmq_vhost }}'
    configure_priv: '.*'
    read_priv: '.*'
    write_priv: '.*'
  notify:
      - restart rabbitmq