---
- name: Install fluentd package
  package:
    name: '{{ fluentd_package_name }}'
    state: present
  when: manage_packages|default(false)

- name: Install fluentd plugins
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ fluentd_plugins }}'
  when: manage_packages|default(false)

- name: Ensure fluentd configuration directory exists
  file:
    path: '{{ fluentd_config_dir }}'
    state: directory
    owner: '{{ fluentd_owner }}'
    group: '{{ fluentd_group }}'
    mode: '{{ fluentd_config_dir_mode }}'

- name: Ensure fluentd config.d directory exists
  file:
    path: '{{ fluentd_config_parts_dir }}'
    state: directory
    owner: '{{ fluentd_owner }}'
    group: '{{ fluentd_group }}'
    mode: '{{ fluentd_config_dir_mode }}'

- name: Create fluentd.conf
  template:
    src: fluentd.conf
    dest: '{{ fluentd_config_file }}'
    owner: '{{ fluentd_owner }}'
    group: '{{ fluentd_group }}'
    mode: '{{ fluentd_config_mode }}'
  notify: restart fluentd

- name: Check if local fluentd certificate exists
  delegate_to: localhost
  stat:
    path: "{{ local_fluentd_ca_cert_path }}"
  register: local_fluentd_ca_cert_path_exists

- name: Read fluentd certificate
  set_fact:
    fluentd_ca_cert: "{{ lookup('file', local_fluentd_ca_cert_path) }}"
  when: local_fluentd_ca_cert_path_exists.stat.exists

- name: Install fluentd certificate
  copy:
    content: '{{ fluentd_ca_cert }}'
    dest: '{{ fluentd_ca_cert_path }}'
    owner: '{{ fluentd_owner }}'
    group: '{{ fluentd_group }}'
    mode: '{{ fluentd_config_mode }}'
  when: fluentd_use_ssl

- name: Activate fluentd service
  service:
    name: '{{ fluentd_service_name }}'
    state: running
    enabled: true
  when: manage_services|default(false)
