---
- name: Enable service ports via iptables
  iptables:
    chain: INPUT
    action: insert
    protocol: "{{ item.protocol }}"
    destination_port: "{{ item.port }}"
    # yamllint disable rule:line-length
    source: "{% if 'source' in item and item.source == 'localhost' %}{{ localhost_ip }}{% else %}{{ item.source|default(omit) }}{% endif %}"
    ip_version: "{% if ('source' in item and item.source|ipv6) or force_ipv6  %}ipv6{% else %}ipv4{% endif %}"
    # yamllint enable rule:line-length
    jump: ACCEPT
  with_items: '{{ firewall_data[firewall_rules] }}'
  when: firewall_manage_rules and firewall_use_iptables
  notify: persist iptables


- name: Enable service ports via firewalld
  firewalld:
    # yamllint disable rule:line-length
    rich_rule: >
      rule
      {% if 'source' in item %}
        family="{% if item.source|ipv6 or force_ipv6 %}ipv6{% else %}ipv4{% endif %}"
        source address="{% if item.source == 'localhost' %}{{ localhost_ip }}{% else %}{{ item.source }}{% endif %}"
      {% elif force_ipv6 %}
        family="ipv6"
      {% endif %}
        port protocol="{{ item.protocol }}" port="{{ item.port }}" accept
    # yamllint enable rule:line-length
    zone: public
    permanent: true
    state: enabled
  with_items: '{{ firewall_data[firewall_rules] }}'
  when: firewall_manage_rules and firewall_use_firewalld
  notify: reload firewalld
