---
- name: Enable service ports via iptables
  delegate_to: "{{ item.delegate|default(inventory_hostname) }}"
  iptables:
      chain: INPUT
      destination_port: "{{ item.port }}"
      jump: ACCEPT
      protocol: "{{ item.protocol }}"
      source: "{{ item.source|default(omit) }}"
  with_items: "{{ firewall_data }}"
  when: firewall_manage_rules and firewall_use_iptables
  notify: persist iptables

- name: Enable service ports via firewalld
  delegate_to: "{{ item.delegate|default(inventory_hostname) }}"
  firewalld:
      permanent: true
      port: "{{ item.port }}/{{ item.protocol }}"
      source: "{{ item.source|default(omit) }}"
      state: enabled
      zone: public
  with_items: "{{ firewall_data }}"
  when: firewall_manage_rules and firewall_use_firewalld
  notify: reload firewalld
