---
- name: Configure http input
  template:
    src: http-input.conf
    dest: '{{ fluentd_config_parts_dir }}/100-http-input.conf'
    owner: '{{ fluentd_owner }}'
    group: '{{ fluentd_group }}'
    mode: '{{ fluentd_config_mode }}'
  notify: restart fluentd

