---
- name: install sensu-server
  yum: 
   name=sensu 
   state=installed

- name: configure sensu
  template: 
   src=templates/{{ item }}.json.j2 
   dest=/etc/sensu/conf.d/{{ item }}.json 
   owner=sensu 
   group=sensu
  with_items:
      - api
      - rabbitmq
      - redis
      - sensu_checks
  notify:
      - restart sensu

- name: ensure sensu is started and enabled at boot 
  service: 
   name={{ item }} 
   state=started 
   enabled=yes
  with_items:
      - sensu-server
      - sensu-api
