---
# yamllint disable rule:line-length
- name: Generate openstack auth args for oschecks
  set_fact:
    os_auth_args: >-
      --os-username :::openstack.username|{{ oscheck_default_username }}:::
      --os-password :::openstack.password|{{ oscheck_default_password }}:::
      --os-tenant-name :::openstack.project_name|{{ oscheck_default_project_name }}:::
      --os-auth-url :::openstack.auth_url|{{ oscheck_default_auth_url }}:::
    os_region_arg: >-
      --region_name :::openstack.region_name|{{ oscheck_default_region_name }}:::
# yamllint enable rule:line-length

# Add the following configuration
# api.json -- it configures the sensu-api (server and client)
# redis.json -- it configures the use of redis for sensu as storage
# sensu_oscheck.json -- it configures the oschecks to be executed on the clients
#    sensu_oschecks.json.j2 is a template with severals templates that can be
#    disabled and configured
- name: Configure sensu
  template:
    src: 'templates/{{ item }}.json.j2'
    dest: '{{sensu_config_path}}/{{ item }}.json'
    owner: '{{ sensu_owner }}'
    group: '{{ sensu_group }}'
  with_items:
    - api
    - redis
    - sensu_oschecks
  notify:
    - restart sensu server services

# This task is needed due to the fact that all the templates used to
# create sensu_oschecks.json can be disabled.
# All these templates end with a coma ','
# The last coma ',' needs to be deleted to not let sensu-server crash
- name: Fix sensu_oschecks
  replace:
    dest: '{{sensu_config_path}}/sensu_oschecks.json'
    regexp: ",\n +}}"
    replace: "\n    }\n}"

- name: Create sensu vhost on rabbitmq
  delegate_to: "{{ item }}"
  rabbitmq_vhost:
    name: '{{ sensu_rabbitmq_vhost }}'
    state: present
  notify:
    - restart rabbitmq
  with_items: "{{ groups.rabbit_hosts }}"

- name: Configure rabbitmq permissions
  delegate_to: "{{ item }}"
  rabbitmq_user:
    user: '{{ sensu_rabbitmq_user }}'
    password: '{{ sensu_rabbitmq_password }}'
    vhost: '{{ sensu_rabbitmq_vhost }}'
    configure_priv: '.*'
    read_priv: '.*'
    write_priv: '.*'
  notify:
    - restart rabbitmq
  with_items: "{{ groups.rabbit_hosts }}"

# This is a workaround for https://github.com/sensu/sensu/issues/1478
- name: Ensure correct ownership on directories
  file:
    path: "{{ item }}"
    state: directory
    owner: '{{ sensu_owner }}'
    group: '{{ sensu_group }}'
    recurse: true
  with_items:
    - '{{ sensu_log_path }}'
    - '{{ sensu_runtime_path }}'
  notify:
    - restart sensu server services

- name: Ensure sensu is started and enabled at boot
  service:
    name: '{{ item }}'
    state: started
    enabled: yes
  with_items:
    - '{{ sensu_server_service_name }}'
    - '{{ sensu_api_service_name }}'
  when: manage_services|default(false)
