---
- name: install sensu
  yum:
   name=sensu
   state=installed

- name: configure rabbitmq on sensu
  template:
   src=templates/{{ item }}.json.j2
   dest=/etc/sensu/conf.d/{{ item }}.json
   owner=sensu
   group=sensu
  with_items:
      - rabbitmq
