---

# The host that collectd will write to using http
collectd_write_http_host: localhost

# The port that collectd will write to using http. This is the default
# port on which fluentd listens for http data. Change to write elsewhere.
collectd_write_http_port: 9880

# The path that collectd will append to the url, after the port.
# For fluentd, this can be used to filter data.
collectd_write_http_path: ""

# The full URL that collectd will write to. Normally should not be changed.
collectd_write_http_url: >
  http://{{ collectd_write_http_host }}:
  {{ collectd_write_http_port }}/
  {{ collectd_write_http_path }}

# List of packages we need to install for write_http to work
collectd_plugins_write_http:
  - collectd-write_http
