---

- name: install gnocchi and services
  package:
    state: present
    name: '{{ item }}'
  with_items: '{{ gnocchi_server_packages }}'
  when: manage_packages|default(false)

- name: install mysql for indexer
  package:
    state: present
    name: '{{ database_packages }}'
  when:
    - manage_packages|default(false)
    - database_host == 'localhost'

- name: start database
  service:
    name: '{{ database_service }}'
    state: started
    enabled: 'yes'
  when: database_host == 'localhost'

