---
fluentd_package_name: fluentd
fluentd_service_name: fluentd
fluentd_config_dir: /etc/fluentd
fluentd_config_file: '{{ fluentd_config_dir }}/fluent.conf'
fluentd_config_parts_dir: '{{ fluentd_config_dir }}/config.d'
fluentd_owner: fluentd
fluentd_group: fluentd
fluentd_config_mode: 0644
fluentd_plugins:
  - rubygem-fluent-plugin-secure-forward
  - rubygem-fluent-plugin-add
fluentd_listen: false
fluentd_use_ssl: false
fluentd_shared_key:
fluentd_ca_cert_path: '{{ fluentd_config_dir }}/ca_cert.pem'
